FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_golang_1.26 AS builder

ARG SOURCE_DIR="/go/src/github.com/openshift/spiffe-spire"
WORKDIR ${SOURCE_DIR}

COPY . .
COPY LICENSE /licenses/.

ENV CGO_ENABLED=1
ENV GOFLAGS=""
ENV GO_BUILD_TAGS=strictfipsruntime,openssl
ENV GOEXPERIMENT=strictfipsruntime

ENV GOTMPDIR=/go-tmp
ENV GOCACHE=/go-cache
ENV GOMODCACHE=/go-mod
RUN mkdir -p ${GOTMPDIR} ${GOCACHE} ${GOMODCACHE}

RUN go build -o bin/spire-server -ldflags '-w -s' -tags ${GO_BUILD_TAGS} cmd/spire-server/main.go \
    && go clean -cache -modcache -i -r \
    && rm -rf ${GOTMPDIR} ${GOCACHE} ${GOMODCACHE}

FROM registry.redhat.io/ubi9/ubi-minimal:latest@sha256:ae09ecc3d754bc1726cbda3e2599cc7839e09fe1cc547ce173cf669b645be3cc

ARG RELEASE_VERSION
ARG COMMIT_SHA
ARG SOURCE_URL
ARG SOURCE_DIR="/go/src/github.com/openshift/spiffe-spire"

COPY --from=builder ${SOURCE_DIR}/bin/spire-server /spire-server
COPY --from=builder /licenses /licenses

USER 65534:65534

LABEL com.redhat.component="spire-server-container" \
      name="zero-trust-workload-identity-manager/spiffe-spire-server-rhel9" \
      version="${RELEASE_VERSION}" \
      summary="SPIRE Server Component" \
      maintainer="Red Hat, Inc." \
      description="SPIRE Server manages SPIFFE identities and issues SVIDs to workloads via the SPIRE Agent" \
      vendor="Red Hat, Inc." \
      release="${RELEASE_VERSION}" \
      io.openshift.tags="spire,identity,spiffe,security" \
      io.openshift.build.commit.id="${COMMIT_SHA}" \
      io.openshift.build.source-location="${SOURCE_URL}" \
      io.openshift.build.commit.url="${SOURCE_URL}/commit/${COMMIT_SHA}" \
      io.k8s.display-name="SPIRE Server" \
      io.k8s.description="Container image for the SPIRE Server component, managing trust and identities in SPIFFE/SPIRE systems" \
      cpe="cpe:/a:redhat:zero_trust_workload_identity_manager:1.1::el9"

ENTRYPOINT ["/spire-server", "run"]
