FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_golang_1.26 AS builder

ARG SOURCE_DIR="/go/src/github.com/openshift/spiffe-spire"
WORKDIR ${SOURCE_DIR}

COPY . .
COPY LICENSE /licenses/.

ENV CGO_ENABLED=1
ENV GOFLAGS=""
ENV GO_BUILD_TAGS=strictfipsruntime,openssl
ENV GOEXPERIMENT=strictfipsruntime

RUN go build -o bin/oidc-discovery-provider -ldflags '-w -s' -tags ${GO_BUILD_TAGS} ./support/oidc-discovery-provider

FROM registry.redhat.io/ubi9/ubi-minimal:latest@sha256:ae09ecc3d754bc1726cbda3e2599cc7839e09fe1cc547ce173cf669b645be3cc

ARG RELEASE_VERSION
ARG COMMIT_SHA
ARG SOURCE_URL
ARG SOURCE_DIR="/go/src/github.com/openshift/spiffe-spire"

COPY --from=builder ${SOURCE_DIR}/bin/oidc-discovery-provider /oidc-discovery-provider
COPY --from=builder /licenses /licenses

USER 65534:65534

LABEL com.redhat.component="oidc-discovery-provider-container" \
      name="zero-trust-workload-identity-manager/spiffe-spire-oidc-discovery-provider-rhel9" \
      version="${RELEASE_VERSION}" \
      summary="SPIRE OIDC Discovery Provider" \
      maintainer="Red Hat, Inc." \
      description="OIDC Discovery Provider allows SPIRE to serve SVIDs via OIDC compliant endpoints" \
      vendor="Red Hat, Inc." \
      release="${RELEASE_VERSION}" \
      io.openshift.tags="spire,identity,oidc,spiffe,security" \
      io.openshift.build.commit.id="${COMMIT_SHA}" \
      io.openshift.build.source-location="${SOURCE_URL}" \
      io.openshift.build.commit.url="${SOURCE_URL}/commit/${COMMIT_SHA}" \
      io.k8s.display-name="OIDC Discovery Provider" \
      io.k8s.description="Container for OIDC Discovery Provider to expose SPIFFE identities via standard OIDC interfaces" \
      cpe="cpe:/a:redhat:zero_trust_workload_identity_manager:1.1::el9"

ENTRYPOINT ["/oidc-discovery-provider"]
