FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_golang_1.26 AS builder

ARG SOURCE_DIR="/go/src/github.com/openshift/spiffe-spire"
WORKDIR ${SOURCE_DIR}

COPY . .
COPY LICENSE /licenses/.

ENV CGO_ENABLED=1
ENV GOFLAGS=""
ENV GO_BUILD_TAGS=strictfipsruntime,openssl
ENV GOEXPERIMENT=strictfipsruntime

RUN go build -o bin/spire-agent -ldflags '-w -s' -tags ${GO_BUILD_TAGS} cmd/spire-agent/main.go

FROM registry.redhat.io/ubi9/ubi-minimal:latest@sha256:ae09ecc3d754bc1726cbda3e2599cc7839e09fe1cc547ce173cf669b645be3cc

ARG RELEASE_VERSION
ARG COMMIT_SHA
ARG SOURCE_URL
ARG SOURCE_DIR="/go/src/github.com/openshift/spiffe-spire"

COPY --from=builder ${SOURCE_DIR}/bin/spire-agent /spire-agent
COPY --from=builder /licenses /licenses

USER 0:0

LABEL com.redhat.component="spire-agent-container" \
      name="zero-trust-workload-identity-manager/spiffe-spire-agent-rhel9" \
      version="${RELEASE_VERSION}" \
      summary="SPIRE Agent Component" \
      maintainer="Red Hat, Inc." \
      description="SPIRE Agent runs on each node and is responsible for issuing SVIDs to workloads via the workload API" \
      vendor="Red Hat, Inc." \
      release="${RELEASE_VERSION}" \
      io.openshift.tags="spire,identity,spiffe,security" \
      io.openshift.build.commit.id="${COMMIT_SHA}" \
      io.openshift.build.source-location="${SOURCE_URL}" \
      io.openshift.build.commit.url="${SOURCE_URL}/commit/${COMMIT_SHA}" \
      io.k8s.display-name="SPIRE Agent" \
      io.k8s.description="Container image for the SPIRE Agent component, responsible for workload authentication" \
      cpe="cpe:/a:redhat:zero_trust_workload_identity_manager:1.1::el9"

ENTRYPOINT ["/spire-agent", "run"]
